server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
  shutdown: graceful
  error:
    include-exception: off
    include-stacktrace: never
    include-message: never

spring:
  profiles:
    active: default
  config:
    import:
      - classpath:config/common.yaml
#      - classpath:config/h2.yaml
#      - classpath:config/postgres.yaml

  application:
    name:  kboot-axon

  mongodb:
    embedded:
      version: 3.2.3
