spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/eventstoredb"
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:PNvHnvLzxH}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
