spring:
  data:
    mongodb:
      uri: mongodb://root:${MONGODB_PASSWORD}@mongodb-0.mongodb-headless,mongodb-1.mongodb-headless,mongodb-2.mongodb-headless

      database: kboot-axon-db
      auto-index-creation: true

#  mongodb:
#    embedded:
#      version: 3.2.3
