spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/eventstoredb"
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:PNvHnvLzxH}

  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always

#logging.level:
#  org.hibernate:
#    SQL: DEBUG
#    type.descriptor.sql.BasicBinder: TRACE

---
#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
#
#  datasource:
#    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/eventstoredb"
#    username: ${POSTGRES_USER:postgres}
#    password: ${POSTGRES_PASSWORD:PNvHnvLzxH}
#
#logging.level:
#  org.hibernate:
#    SQL: DEBUG
#    type.descriptor.sql.BasicBinder: TRACE
