server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
  shutdown: graceful
  error:
    include-exception: off
    include-stacktrace: never
    include-message: never
spring:
  profiles:
    active: default
    include:
      - common
#      - h2
#      - postgres
  application:
    name:  kboot-axon
