spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
