apiVersion: batch/v1
kind: Job
metadata:
  name: eventstoredb
spec:
  completions: 1
  template:
    spec:
      containers:
      - name: eventstoredb
        image: bitnami/postgresql:latest
        command: ["createdb"]
        args: ["-h","postgresql", "-U", "postgres", "eventstoredb" ]
        env:
        - name: PGPASSWORD
          value: PNvHnvLzxH
      restartPolicy: Never

