version: "3"
services:
  postgres:
    container_name: postgres-axon
    image: "postgres:12"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: eventstoredb
      PGDATA: "/data/postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /var/lib/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres-data:
