apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: c3smonkey/template
    newName: kboot-axon-service
    newTag: latest

namespace: default

commonLabels:
  app: kboot-axon-service
  appGroup: demo

resources:
  - ../../base

# Patch Deployment
patchesStrategicMerge:
  - use-postgres.yaml
  - patch-service.yaml
  - patch-spring-profile.yaml

# ConfigMap
configMapGenerator:
  - files:
      - config-files/application.yaml
    name: kboot-axon-service
    options:
      disableNameSuffixHash: true
