apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: kboot-axon-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
