apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: kboot-axon-service
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgresql-password

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_HOST
              value: postgresql
